#!/usr/bin/env bash
# Inference: generate visible faces for every thermal test image, then score them.
#   bash scripts/test.sh                      # stage-2 LDM, newest checkpoint
#   STAGE=3 bash scripts/test.sh              # stage-3 ControlNet
#   CKPT=/path/to.ckpt bash scripts/test.sh
# NOTE: test_step caches the first batch size, so BATCH must divide the test-set size exactly.
set -e
cd "$(dirname "$0")/.."
source scripts/env.sh
STAGE="${STAGE:-2}"
BATCH="${BATCH:-42}"
if [ "$STAGE" = "3" ]; then
  CFG=configs/_resolved/stage3_controlnet.yaml; TAG="${TAG:-cldm}"; CKPT="${CKPT:-$(latest_ckpt stage3_controlnet)}"
else
  CFG=configs/_resolved/stage2_ldm.yaml;        TAG="${TAG:-ldm}";  CKPT="${CKPT:-$(latest_ckpt stage2_ldm)}"
fi
[ -f "$CKPT" ] || { echo "no checkpoint found; train stage $STAGE first or set CKPT"; exit 1; }
# configs/_resolved/* is generated by the training scripts and is gitignored, so it may be
# absent (fresh clone, cleaned tree). Regenerate it here from the template + checkpoints
# rather than forcing the user to re-run training.
if [ ! -f "$CFG" ]; then
  mkdir -p configs/_resolved
  VIS_CKPT="${VIS_CKPT:-$(latest_ckpt stage1_vqvae_vis)}"
  TH_CKPT="${TH_CKPT:-$(latest_ckpt stage1_vqvae_th)}"
  if [ "$STAGE" = "3" ]; then
    sed -e "s|__STAGE1A_VIS_CKPT__|$VIS_CKPT|" -e "s|__STAGE1B_TH_CKPT__|$TH_CKPT|" \
        -e "s|__CLDM_INIT_CKPT__|outputs/stage3_controlnet/cldm_init.ckpt|" \
        configs/stage3_controlnet.yaml > "$CFG"
  else
    sed -e "s|__STAGE1A_VIS_CKPT__|$VIS_CKPT|" -e "s|__STAGE1B_TH_CKPT__|$TH_CKPT|" \
        configs/stage2_ldm.yaml > "$CFG"
  fi
  echo "[test] regenerated $CFG"
fi
# DataModuleFromConfig.prepare_data() instantiates EVERY split (train/val/test), not just
# the one being used, so all of them must point at a directory that exists.
OUT="outputs/$TAG/test_images"; mkdir -p "$OUT"; rm -f "$OUT"/*.png 2>/dev/null || true
GPU0="${GPUS%%,*}"
echo "[test] ckpt=$CKPT -> $OUT (single GPU $GPU0, batch $BATCH)"
python test.py --base "$CFG" --ckpt "$CKPT" save_test_dir="$OUT" \
  lightning.trainer.gpus="\"$GPU0\"" data.params.batch_size=$BATCH \
  $(data_overrides)
echo "[test] scoring against $DATA_ROOT/test/VIS"
CUDA_VISIBLE_DEVICES="$GPU0" python scripts/eval_metrics.py \
  --pred "$OUT" --gt "$DATA_ROOT/test/VIS" --size 128 --device cuda \
  --lpips-net alex --fid-impl pytorch-fid --out "outputs/$TAG/metrics.json"
